name: Cron Job and Deploy to Vercel

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
  VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}

on:
  schedule:
    - cron: '15 15 * * *' # KST 자정에 실행

jobs:
  run-cron-job:
    runs-on: ubuntu-latest
    steps:
      # 1. Vercel API 호출
      - name: Make HTTP request to Vercel API
        run: |
          curl -v -X GET https://mypat.vercel.app/api/cron \
          -H "Authorization: Bearer ${{ secrets.VERCEL_TOKEN }}"

      # 2. Vercel 배포
      - name: Deploy to Vercel
        run: npx vercel deploy --prod --token ${{ secrets.VERCEL_TOKEN }} \
          --org ${{ secrets.VERCEL_ORG_ID }} --project ${{ secrets.VERCEL_PROJECT_ID }}
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
