name: Cron Job and Deploy to Vercel

on:
  schedule:
    - cron: '15 15 * * *' # KST 자정에 실행

jobs:
  run-cron-job:
    runs-on: ubuntu-latest
    steps:
      # 1. Vercel API 호출
      - name: Make HTTP request to Vercel API
        run: |
          curl -v -X GET https://mypat.vercel.app/api/cron \
          -H "Authorization: Bearer ${{ secrets.MYPET }}"

      # 2. Vercel 배포
      - name: Deploy to Vercel
        run: npx vercel deploy --prod
        env:
          VERCEL_TOKEN: ${{ secrets.MYPET }}
