name: Cron Job for Group Purchase

on:
  schedule:
    # 매일 자정에 실행
    - cron: '0 0 * * *' # UTC 기준으로 자정

jobs:
  run-cron-job:
    runs-on: ubuntu-latest
    steps:
      - name: Make HTTP request to Vercel API
        run: |
          curl -X GET https://mypat.vercel.app/api/cron
