name: Cron Job for Group Purchase

on:
  schedule:
    # 매일 자정에 실행
    - cron: '0 15 * * *'

jobs:
  run-cron-job:
    runs-on: ubuntu-latest
    steps:
      - name: Make HTTP request to Vercel API
        run: |
          curl -v -X GET https://mypat.vercel.app/api/cron
